local

diff --git a/git b/git
--- a/git
+++ b/git
@@ -14,4 +14,58 @@ para actualizar los cambios que se realizaron en los archivos
 
 # git add .
 
-# git commit -m "nombre" 
+# git commit -m "nombre"
+
+
+
+*******************************
+
+Monitoreo replica
+
+#!/bin/bash
+
+fecha=$(date '+%d-%m-%Y')
+
+MAILTO='infraestructura.mn@kionetworks.com'
+#Here we declare variable MAILTO with email address
+
+SUBJECT="Estatus Replica Cluster AVON "$fecha
+#Here we declare variable SUBJECT with subject of email
+
+SUBJECT_ERR="Estatus Replica Cluster AVON "$fecha" (ERROR)"
+
+MAILX='mailx'
+#Here we declare variable MAILX with mailx command that will send email
+
+MAIL_BODY=$(mysql --user='root' -p"DBmnr00t.2019%" -e "show slave 'master01' status \G")
+
+which $MAILX > /dev/null 2>&1
+#Here we check if mailx command exist
+
+if ! [ $? -eq 0 ]
+#We check exit status of previous command if exit status not 0 this mean that mailx is not installed on system
+then
+          echo "Please install $MAILX"
+#Here we warn user that mailx not installed
+          exit 1
+#Here we will exit from script
+fi
+
+cd $DIR
+#To check real used size, we need to navigate to folder
+
+replica_status=$(mysql --user='root' -p"DBmnr00t.2019%" -e "show slave 'master01' status \G" | grep "Error" | awk '{ print $2 }')
+run_status_ok="Slave_SQL_Running_State: Slave has read all relay log; waiting for the slave I/O thread to update it"
+
+running_status=$(mysql --user='root' -p"DBmnr00t.2019%" -e "show slave 'master01' status \G" | grep "Slave_SQL_Running_State:")
+
+#Si se encuentran errores en la salida del estatus, se imprime error
+
+ if [[ $replica_status == "" ]] && [[ $running_status == *"$run_status_ok"* ]]
+ then
+   MAIL_BODY=$'\n'"No se encontró ningún error en el estatus de la réplica "$'\n'$'\n'$MAIL_BODY
+   echo -e "$MAIL_BODY" | $MAILX -s "$SUBJECT" "$MAILTO"
+ else
+   MAIL_BODY=$'\n'"Se presentaron los siguientes errores en la réplica "$'\n'$'\n'$MAIL_BODY
+   echo -e "$MAIL_BODY" | $MAILX -s "$SUBJECT_ERR" "$MAILTO" -c "servicedesk@kionetworks.com"
+ fi
